# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d0b639a5c3a5a9c919820430d4087ded128a795b69af6f4c2786a83bce4176102ff9a1ffe5b6b272c26f3fe82f5bff258f3cf9ab91f385127d0a4acd9025ac5

test:
  secret_key_base: 21e3a376684eeed4075215aca859976de9e80eeb4cabe2e54b109ef6f394e21fecb54c788355e35374acbeec37c9c524cc1ffe89b7d3fa169444052d82f51510

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
